### ISSUE TITLE
Any examples of multiple cameras capturing depth information?

### ISSUE THREAD

**Issue by DK-ZhangYi** [StanfordVL/BEHAVIOR-1K#1015]
I used two cameras to collect RGB and depth information in Omnibizon. I set the camera position and orientation using cam_1. set_position orientation (cam_1-position, quat1), but I found that when the two cameras were using their own set positions and quaternion poses for coordinate conversion, the point clouds could not align. Can anyone give me any suggestions for checking? In addition, after setting it up, I also checked the settings using cam_1. get_position _orientation (), and the obtained parameters were consistent with the set parameters. Is the coordinate system of the camera in Omnibizon equivalent to the depth acquisition reference plane?

**Comment by yizhangdanikor** [comment]
I am using OmniGibson v1.1.1
